name: Format Check

on:
  push:
    branches:
      - main  # Runs on pushes to main branch
  pull_request:
    branches:
      - main  # Runs on PRs to main branch

jobs:
  check-for-flag-file:
    if: github.repository != 'evmckinney9/python-template'
    runs-on: ubuntu-latest
    outputs:
      continue: ${{ steps.flag-check.outputs.continue }}
    steps:
      - uses: actions/checkout@v4
      - name: Check for template_flag.yml
        id: flag-check
        run: |
          if [ ! -f .github/template_flag.yml ]; then
            echo "continue=true" >> $GITHUB_OUTPUT
          else
            echo "continue=false" >> $GITHUB_OUTPUT
          fi

  run-format-check:
    needs: check-for-flag-file
    if: needs.check-for-flag-file.outputs.continue == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: 'pip'
          cache-dependency-path: "**/pyproject.toml"
      - name: Install pre-commit packages
        run: pip install .[format] --quiet
      - name: Run pre-commit
        run: pre-commit run --all-files
